name: lapa-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - chex==0.1.82
      - click==8.3.0
      - cloudpickle==3.1.1
      - datasets==2.13.0
      - decorator==5.2.1
      - decord==0.6.0
      - dill==0.3.6
      - einops==0.8.1
      - etils==1.13.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.120.1
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - flax==0.7.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gast==0.6.0
      - gcsfs==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.4.1
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanize==4.14.0
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipython==8.37.0
      - jax==0.4.23
      - jaxlib==0.4.23+cuda12.cudnn89
      - jedi==0.19.2
      - jinja2==3.1.6
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.14
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.28.7
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.3.1
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.1.7
      - optree==0.17.0
      - orbax-checkpoint==0.5.10
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - scipy==1.12.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.1
      - simplejson==3.20.2
      - simsimd==6.5.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.49.0
      - stringzilla==4.2.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorstore==0.1.78
      - termcolor==3.2.0
      - tiktoken==0.12.0
      - tokenizers==0.13.3
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.29.2
      - triton==3.0.0
      - tux==0.0.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.22.2
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/elias/miniconda3/envs/lapa-env
