name: openvla-env
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - aom=3.6.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cuda-cccl=12.9.27
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.4.1
  - cuda-compiler=12.9.0
  - cuda-crt-dev_linux-64=12.9.41
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.26
  - cuda-cupti=12.4.127
  - cuda-cuxxfilt=12.9.19
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.9.79
  - cuda-driver-dev_linux-64=12.9.79
  - cuda-gdb=12.9.79
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.6.2
  - cuda-libraries-static=12.9.1
  - cuda-nsight=12.9.79
  - cuda-nvcc=12.9.41
  - cuda-nvcc-dev_linux-64=12.9.41
  - cuda-nvcc-impl=12.9.41
  - cuda-nvcc-tools=12.9.41
  - cuda-nvcc_linux-64=12.9.41
  - cuda-nvdisasm=12.9.88
  - cuda-nvml-dev=12.9.79
  - cuda-nvprof=12.9.79
  - cuda-nvprune=12.9.19
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvrtc-static=12.9.86
  - cuda-nvtx=12.4.127
  - cuda-nvvm-dev_linux-64=12.9.41
  - cuda-nvvm-impl=12.9.41
  - cuda-nvvm-tools=12.9.41
  - cuda-nvvp=12.9.79
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.4.1
  - cuda-sanitizer-api=12.9.79
  - cuda-toolkit=12.4.1
  - cuda-tools=12.4.1
  - cuda-version=12.9
  - cuda-visual-tools=12.6.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - expat=2.7.1
  - ffmpeg=4.2.2
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.14.1.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - imageio=2.37.0
  - intel-openmp=2023.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - kernel-headers_linux-64=3.10.0
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcublas-static=12.9.1.4
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcufft-static=11.4.1.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcufile-static=1.14.1.1
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurand-static=10.3.10.19
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusolver-static=11.7.5.82
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libcusparse-static=12.5.10.65
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnpp-static=12.4.1.87
  - libnvfatbin=12.9.82
  - libnvfatbin-dev=12.9.82
  - libnvfatbin-static=12.9.82
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjitlink-static=12.9.86
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libnvjpeg-static=12.4.0.76
  - libopus=1.3.1
  - libpng=1.6.39
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - nsight-compute=2025.2.1.3
  - nspr=4.35
  - nss=3.89.1
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.18
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.5
  - setuptools=78.1.1
  - sqlite=3.50.2
  - sympy=1.14.0
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - x264=1!157.20191217
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - array-record==0.8.1
      - astunparse==1.6.3
      - attrs==25.3.0
      - bddl==3.6.0
      - bitsandbytes==0.47.0
      - cachetools==5.5.2
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - daqp==0.7.2
      - dlimp==0.0.1
      - dm-tree==0.1.9
      - draccus==0.8.0
      - easydict==1.13
      - einops==0.8.1
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.2
      - flash-attn==2.5.5
      - flatbuffers==25.9.23
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.75.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - joblib==1.5.2
      - json-numpy==2.1.1
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupytext==1.17.3
      - keras==2.15.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - llvmlite==0.45.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mink==0.0.13
      - ml-dtypes==0.2.0
      - mujoco==3.3.6
      - mypy-extensions==1.1.0
      - nbformat==5.10.4
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.62.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opencv-python==4.9.0.80
      - openexr==3.4.0
      - openvla==0.0.3
      - opt-einsum==3.4.0
      - packaging==25.0
      - peft==0.11.1
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - promise==2.3
      - protobuf==4.21.12
      - psutil==7.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pyyaml-include==1.4.1
      - qpsolvers==4.8.1
      - referencing==0.36.2
      - regex==2025.9.18
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - robosuite==1.4.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.39.0
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - termcolor==3.1.0
      - timm==0.9.10
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - trimesh==4.8.2
      - triton==2.2.0
      - typeguard==2.13.3
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - wandb==0.22.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
      - zipp==3.23.0
prefix: /home/elias/miniconda3/envs/openvla-env
